### ISSUE TITLE
dataset issue

### ISSUE THREAD

**Issue by zp9187** [IBM/ICDAR2021-SLP#1]
Can we use the pdf file of test dataset?

**Comment by zp9187** [comment]
Please further clarify on the available datasets we can use (only raw image allowed or both image and pdf are allowed).
thx~

**Comment by ajjimeno** [comment]
Thank you for your question and interest in the challenge. In principle, it would be interesting to have methods relying on image data, which is provided for the challenge. Using the PDF is not forbidden, since it is complementary information. Please mention the data sources that you use in the description of your submission.

**Comment by zp9187** [comment]
> Thank you for your question and interest in the challenge. In principle, it would be interesting to have methods relying on image data, which is provided for the challenge. Using the PDF is not forbidden, since it is complementary information. Please mention the data sources that you use in the description of your submission.

**Background**: Coordinates and categories of texts/ image/ table in a document can be precisely determined by parsing the corresponding pdf file using pdfminer.

**Question**:
If PDF of test dataset is not forbidden, do you mean the following operations are allowed?

1. parsing texts in pdf (coordinates and contents)
2. parsing image/ table in pdf (coordinates and categories)

I think we should clarify on what we can and what we cannot do with the PDF file (e.g. 1 is allowed and 2 is forbidden, or both are allowed) to ensure the fairness and significance of the challenge.

Looking forward to your reply.
Many Thanks.

**Comment by ajjimeno** [comment]
Thank you for your feedback. Our initial idea is that people consider the images as source since solutions might be more general (e.g. not bound to PDF), but we should allow participants to explore. The documents in the biomedical domain that we are considering are PDFs, so it would be great to learn what is your performance using PDFs and tools such as PDFMiner. In previous experience, PDFMiner did not have the performance that we expected, but it would be great to find out about your outcomes.
